name: Generate Sitemap

on:
  push:
    branches:
      - main  # Jalankan otomatis setiap ada perubahan di branch main
  schedule:
    - cron: '0 0 * * 0'  # Jalankan setiap minggu (Minggu, pukul 00:00 UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

          for file in *.html; do
            if [ "$file" != "404.html" ]; then
              echo "  <url>" >> sitemap.xml
              echo "    <loc>https://jakartabersatu.github.io/${file}</loc>" >> sitemap.xml
              echo "    <changefreq>daily</changefreq>" >> sitemap.xml
              echo "    <priority>0.8</priority>" >> sitemap.xml
              echo "  </url>" >> sitemap.xml
            fi
          done

          echo '</urlset>' >> sitemap.xml

      - name: Commit and push changes
  run: |
    git config --global user.name "your-username"
    git config --global user.email "your-email@example.com"
    git add sitemap.xml
    git commit -m "Update sitemap.xml [Auto Generated]" || echo "No changes to commit"
    git push https://your-username:${{ secrets.PAT_TOKEN }}@github.com/jakartabersatu/jakartabersatu.github.io.git HEAD:main
