name: Generate Sitemap

on:
  push:
    branches:
      - main  # Workflow dijalankan saat push ke branch main
  schedule:
    - cron: '0 0 * * 0'  # Workflow dijalankan setiap minggu (Minggu, pukul 00:00 UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          for file in *.html; do
            if [ "$file" != "404.html" ]; then
              echo "  <url>" >> sitemap.xml
              echo "    <loc>https://jakartabersatu.github.io/${file}</loc>" >> sitemap.xml
              echo "    <changefreq>daily</changefreq>" >> sitemap.xml
              echo "    <priority>0.8</priority>" >> sitemap.xml
              echo "  </url>" >> sitemap.xml
            fi
          done
          echo '</urlset>' >> sitemap.xml

      - name: Commit and push changes
        run: |
          git config --global user.name "jakartabersatu"
          git config --global user.email "hendrikyss151@gmail.com"
          git add sitemap.xml
          git commit -m "Update sitemap.xml [Auto Generated]" || echo "No changes to commit"
          git push https://jakartabersatu:${{ secrets.PAT_TOKEN }}@github.com/jakartabersatu/jakartabersatu.github.io.git HEAD:main
